name: Django CI/CD to Kubernetes

on:
  push:
    branches: [ "main" ]

env:
  IMAGE_NAME: dailyhealer/web
  IMAGE_TAG: 1.0

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"

    - name: Install uv
      run: curl -LsSf https://astral.sh/uv/install.sh | sh

    - name: Install dependencies
      working-directory: web
      run: uv sync

    - name: Django checks
      working-directory: web
      run: |
        uv run python manage.py check
        uv run python manage.py makemigrations --check --dry-run

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: docker build -t ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} web

    - name: Push Docker image
      run: docker push ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

    - name: Setup Minikube
      uses: manusa/actions-setup-minikube@v2.5.0
      with:
        minikube version: '1.30.1'
        kubernetes version: '1.28.0'

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f k9s/apps/web.yaml
        kubectl get pods
